### ISSUE TITLE
AudioEncoder fails in call to ff_init_filter_graph

### ISSUE THREAD

**Issue by martenrichter** [ennuicastr/libavjs-webcodecs-polyfill#15]
I finally got the libAV setup to work. 
Unfortunately, I ran into an issue with the AudioEncoder.
I try to encode audio samples coming from the Webcam/Microphone to opus.
The encoding fails at the call to:
`await libav.ff_init_filter_graph("anull", filter_ctx, self._filter_out_ctx)`
the arguments are:

Input:
sample_rate: 48000
sample_fmt: 8
channel_layout: 4 

Output:
channel_layout: 4
frame_size: 960
sample_fmt: 3
sample_rate: 48000

So basically it should convert from double to float.
However, it fails internally at 

avfilter_graph_parse
with return value -28
meaning:
"Failed to initialize filters: Invalid argument\n"
Not really helpful though.

One thing to note is that I am running several AudioEncoders in parallel. But if I understood the architecture correctly, this should not be a problem.

Can you point me toward a possible solution? If it is something to fix or a feature to add. I will create a PR.

**Comment by Yahweasel** [comment]
Yeah, that's libav's error style, not very helpful X-D . I imagine the version of libav you have does not have 64-bit float support. It would only enable it if any decoder or encoder it supports uses it. You'd have to add something like the `pcm_f64le` decoder, or just do the float-to-float conversion yourself.

**Comment by martenrichter** [comment]
Well, it is the bundled opus build from libav.js. Thanks this is very helpful. I will then do the conversion myself. Thanks, I analyzed the problem for 2 hours..... so this is very helpful.

**Comment by martenrichter** [comment]
Ok, so I should have gone with a bigger one such as lite. (building myself does not work well with the npm package manager).
Opus was my natural choice since my main aim is to provide a compatibility layer for ios devices, which support video WebCodecs but not audio, which currently (and hopefully that changes) do not allow non webkit based browsers.

**Comment by Yahweasel** [comment]
I don't know the rest of your context, but if this is all you need, then the opus one should be sufficient, you just need to use "aresample" instead of "anull". If you need _anything_ more than that, then yeah, you probably want lite.

**Comment by martenrichter** [comment]
Ok, then my task will be to add a PR that detects missing anull and does a replacement with aresample.

**Comment by Yahweasel** [comment]
It's probably not even necessary to detect if anull is missing. I should have probably used "aresample" here in the first place, as that will always be the right option (insofar as none of this can work without aresample)

**Comment by martenrichter** [comment]
Yes, aresample is the right way to go:
https://github.com/ennuicastr/libavjs-webcodecs-polyfill/pull/16

**Comment by martenrichter** [comment]
Anyway the next thing pops up.
The chromium implementation only supplies metadata on change.
Therefore my code transmits the metadata without checking one to one to remote.
The polyfill passes the metadata at every frame. So what do you think, should I change the behavior on the polyfill or do it in my code. I would guess having a similar behavior on polyfill and original would be beneficial.

**Comment by Yahweasel** [comment]
> Anyway the next thing pops up. The chromium implementation only supplies metadata on change. Therefore my code transmits the metadata without checking one to one to remote. The polyfill passes the metadata at every frame. So what do you think, should I change the behavior on the polyfill or do it in my code. I would guess having a similar behavior on polyfill and original would be beneficial.

No, the most beneficial is to follow the spec. If Chrome isn't following the spec, then one of those two should be changed, not libavjs-webcodecs-polyfill. While the spec isn't always 100% clear, it provides no description of outputting a chunk of data without associated metadata. The one thing where that's unclear is that it *does* document that metadata is an optional parameter of the output callback, and yet it *doesn't* document any situation in which that optional parameter would not be included. But, the polyfill is following the spec.

**Comment by martenrichter** [comment]
Well, I did not say the polyfill is not following the spec. But in usual containers such as MP4 extradata is written only once for a given parameter set, so I found Chrome's behavior relatively logical.... In this case, I will filter it in my code.

**Comment by martenrichter** [comment]
But actually, I am referring to extra data.

**Comment by martenrichter** [comment]
I stumbled upon a related issue. Using avresample works fine so far, however I have configured as input mono. However, after Encoding and Decoding it, I got stereo output.

I am not completely at the bottom of the issue, but I again stumbled upon the extradata.
You are correct, that it is allow to output extra and the WebCodec spec is not completely clear about it.
But for opus you find here: https://www.w3.org/TR/webcodecs-opus-codec-registration/#opus-encoder-config
https://www.w3.org/TR/webcodecs-opus-codec-registration/#audiodecoderconfig-description
the specification, when you are allowed to output extradata for opus:
https://www.w3.org/TR/webcodecs-opus-codec-registration/#opus-bitstream-format
I have specified as format "opus", now I speculate, that the bitstream format coming from ffmpeg may be ogg instead of opus?
But have not verified this. (Of course, this is crucial for me, since I like to operate the polyfill together with the browser implementation on different devices and they should match).

If you can tell me were to look, I will try to investigate it further and hopefully provide a universal patch.

**Comment by martenrichter** [comment]
Ok, I found the origin for the sudden widening to stereo.
 A stereo libopus decoder will also decode mono opus and turn it into stereo.
I think the channel information is not reaching:
https://github.com/FFmpeg/FFmpeg/blob/247e977953b1fb43c145d21074a7238a05220d4d/libavcodec/libopusdec.c#LL58C70-L58C91
So either the extradata has to be fed (which should not be there for 'opus' format) or the channel layout. I will look tomorrow into how this can also be set in the AudioDecoder in a general way. And I mean at least the channel layout.

**Comment by martenrichter** [comment]
So I went through the spec more thoroughly and I also looked at the implementation in chromium, ffmpeg and  libopus.

The AudioEncoder implementation in Chromium:
https://github.com/chromium/chromium/blob/7ddcbf6595ed0a7651e462e16268d42f3af75c7f/media/audio/audio_opus_encoder.cc#L269
(I hope it is the one used in Webcodecs).
Use calls to libopus. As far as I have tracked the calls, it seems to use functions that do not involve self-delimiting frames as specified in:
https://datatracker.ietf.org/doc/html/rfc6716#appendix-B
It also emits intentionally extradata only once, since per opus spec, it is not allowed to change within the bitstream.
That means at least in this object, it is not opus in ogg, so also chromium does not seem to support the ogg format and should only emit opus bitstream format.
However, I can not tell so far, if it is added somewhere else in chromium.
The same is true for the encoder used by libav.js in ffmpeg, it also calls libopus without the flag for self-delimiting frames and should create opus bitstream.

Chromium passes for the ffmpegaudiodecoder (which is used for decoding) the extradata as well as the number of channels, see here:
https://github.com/chromium/chromium/blob/7ddcbf6595ed0a7651e462e16268d42f3af75c7f/media/ffmpeg/ffmpeg_common.cc#L464
I will try to patch this in a way to be applicable to all codecs.

**Comment by Yahweasel** [comment]
Regarding extradata, let me be abundantly clear: I will not accept a patch that changes it to only send extradata when it changes, because this would violate the spec. I don't care what Chrome does, and I don't care what the logical thing to do is. If the spec is wrong, you should be filing a bug with the WebCodecs spec. When the WebCodecs spec has been updated to be consistent with Chrome, then I'm happy to update libavjs-webcodecs-polyfill to be consistent with Chrome. This polyfill is not supposed to be a Chrome emulator, it's following the spec.

Regarding stereo, there's presumably some way to convince libav to tell libopus the right thing. I use mono libopus all the time, so I'm surprised you're encountering this issue... presumably some data somewhere is convincing it to do something weird.

**Comment by martenrichter** [comment]
Regarding extradata, I have already a working code, that filters the additional stuff out. So I do not care, but I still think, that it is not really following the specs, since extra data is not allowed to change for opus. But let's agree to disagree.

But actually, the text was not about outputting extradata, apparently, the spec uses for the decoder to identify the different bitstream formats the fact if extradata is passed or not. That is a different point. It is in the webcodecs registry ([it is somehere above](https://www.w3.org/TR/webcodecs-opus-codec-registration/#audiodecoderconfig-description)) and your code only supports opus, which fine, but should fails if the extradata is passed.  For flac and vorbis for example, extradata is always mandatory to be passed to the decoder during configure (also in the webcodecs registry spec for the respective format).

Regarding the stereo stuff are you using it inside the WebCodecs polyfill or outside? (And is the output really mono, because it works (probably I have not sent it to the speaker), but is stereo, so check the output please).
I think I have tracked it down, that the codec probably needs to have the channel number at init. My main problem to test it, is that ``ff_init_decoder`` can be fed with codecs parameters and I need to know the ffmpeg codec_id beforehand...., and counting the enum is not a reliable way.... That what I have been doing since the morning (middle european time).

**Comment by Yahweasel** [comment]
How odd, libopus is indeed always outputting stereo if you don't ask it nice, rather than following the data.

The type of the "name" parameter to ff_init_decoder is string | number. You do not need the numeric ID, just "libopus". It should not be necessary to fill in fields of codecpar that aren't relevant, such as the codec_id.

**Comment by martenrichter** [comment]
> How odd, libopus is indeed always outputting stereo if you don't ask it nice, rather than following the data.
Actually, this is by design, at least that is what I have read, you can choose, what the output should be and since my whole pipeline after this mono, I am investing time to fix this for the polyfill.

> 
> The type of the "name" parameter to ff_init_decoder is string | number. You do not need the numeric ID, just "libopus". It should not be necessary to fill in fields of codecpar that aren't relevant, such as the codec_id.
I have try this but it failed. I just put in the number of channels and bitrate, as recommended by the spec. (Btw, the channel api of ffmpeg is deprecated, I have written some code for libav.js to retain the old api, if you like this, but currently, it is not urgent.)

The reason why it fails is that `` avcodec_parameters_to_context`` copy also the codec id to the context and overwrites the id:
https://ffmpeg.org/doxygen/trunk/codec__par_8c_source.html#l00184
since I do not want to touch libAV.js for this, I am trying to figure out what the codecid for the supported codecs. Because I do not want to change to much of the code.

**Comment by Yahweasel** [comment]
Well that's annoying. Anyway, you want avcodec_find_decoder_by_name.

**Comment by martenrichter** [comment]
Sure, but the result AVCodec has no converter in binding.c. I am now thinking, that I check if the options clear the codec_id and the type and if they do I restore it. Anyway, I will figure something out.... minimum possible changes.

Btw. there was a comment in chromium code about libopus behavior and some problems in quality with a special setting to fix it, do you want a pointer, since you are doing a lot with opus and probably care about quality?

**Comment by martenrichter** [comment]
I thought I was almost ready, but it is still outputting stereo. I will probably not solve it this weekend but will continue next weekend. Currently, I am recompiling libav.js with dwarf support for debugging. I know for sure, that this line:
https://github.com/chromium/chromium/blob/7ddcbf6595ed0a7651e462e16268d42f3af75c7f/media/ffmpeg/ffmpeg_common.cc#L464
which need to be fed with the right parameters is the origin of the troubles, but somewhere I am not doing it correctly. At least, the codec is again created.

**Comment by Yahweasel** [comment]
I've just merged fixmonostereo.

**Comment by martenrichter** [comment]
First I hope you get well soon.
Perfect that it is merged, the question is if the same kind of changes should also be applied to video. So far I have no application running for this, and so can not really test it. But for sure depending on the type of bitsream , extra data and other paramters might be needed as well.

**Comment by martenrichter** [comment]
> I've just merged fixmonostereo.

But only for libav.js, you are looking later on the polyfill? (Because both fixes are necessary)

**Comment by Yahweasel** [comment]
Forgot to close this, but I believe it was fixed months ago.
