### ISSUE TITLE
`EncodedVideoChunk#timestamp()` is off by factor 1000

### ISSUE THREAD

**Issue by jlnstrk** [ennuicastr/libavjs-webcodecs-polyfill#33]
Hi there! I'm seeing [`EncodedVideoChunk#timestamp`](https://developer.mozilla.org/en-US/docs/Web/API/EncodedVideoChunk/timestamp) being reported in milliseconds instead of microseconds when encoding. I've tried both AVC (`avc1.6400.28`) and VP9 (`vp09.00.10.08`). I'm getting correct values for audio (Opus).

I can try to set up a minimal repro when I have time, but maybe you already have an idea what might be going on.

**Comment by Yahweasel** [comment]
Matroska (and thus WebM) use milliseconds as their (very stupid) timebase. It's possible that I simply made a mistake and chose a timebase I was familiar with somewhere. A minimal repro would be appreciated.

**Comment by jlnstrk** [comment]
My apologies, the issue was not with this polyfill but with another that produces the `VideoFrame`s I am passing to the encoder, which I failed to check.
