### ISSUE TITLE
metadata argument of AudioEncoder output callback doesn't match spec

### ISSUE THREAD

**Issue by xlf1024** [ennuicastr/libavjs-webcodecs-polyfill#5]
according to spec, the second argument of the [`EncodedAudioChunkOutputCallback`](https://w3c.github.io/webcodecs/#callbackdef-encodedaudiochunkoutputcallback) receives an optional [`EncodedAudioChunkMetadata`](https://w3c.github.io/webcodecs/#dictdef-encodedaudiochunkmetadata) which in turn contains an optional [`AudioDecoderConfig`](https://w3c.github.io/webcodecs/#dictdef-audiodecoderconfig)[`decoderConfig`](https://w3c.github.io/webcodecs/#dom-encodedaudiochunkmetadata-decoderconfig), which is the same type as supplied to [`AudioDecoder`](https://w3c.github.io/webcodecs/#audiodecoder)`::`[`configure`](https://w3c.github.io/webcodecs/#dom-audiodecoder-configure)`(`[`AudioDecoderConfig`](https://w3c.github.io/webcodecs/#dictdef-audiodecoderconfig)` config)`.

This polyfill passes a `Uint8Array` instead, which from the stacktrace looks like it directly the codec extradata that seems like it should be in `decoderConfig.description`.

Also, if I understood the spec correctly, `decoderConfig` should be passed to `AudioDecoder::configure`, but this polyfill's implementation doesn't seem to read the description property at all.

**Comment by Yahweasel** [comment]
Hmmm, I indeed seemed to have missed something around decoder configuration. Probably a case of "just get it working" since this argument wasn't important for any of the codecs I was concerned with at the time :) . Will fix.

**Comment by Yahweasel** [comment]
Fixed in [712672c](https://github.com/ennuicastr/libavjs-webcodecs-polyfill/commit/712672c719961f2b4e52c1b8e7f6128ab6647944)
